services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${POSTGRES_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          # DBユーザー名
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}       # DBパスワード
      POSTGRES_DB: ${POSTGRES_NAME}       # 作成するデータベース名
      POSTGRES_HOST: ${POSTGRES_HOST}       # 作成するデータベース名
    ports:
      - "5432:5432"                    # ローカル:コンテナ
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net

volumes:
  db-data:                             # データ永続化ボリューム

networks:
  backend-net:
    driver: bridge